### ISSUE TITLE
Encoding error in tab "Translate external text files"

### ISSUE THREAD

**Issue by GotrekGurnisson** [dfint/df-translation-client#10]
Hi,
Win 10 Pro.
`pip 21.0.1 from c:\users\Gotrek\appdata\local\programs\python\python38-32\lib\site-packages\pip (python 3.8)`

I got another error and I am not sure if it is program bug or I have somehow corrupted/broken python

1) start program
2) on 3rd tab choose required fields
3) download files from transifex (Czech lang but I got same error with English files also)
4) Search button works perfectly but Translate button throw error. See screens and details. I got error for both encoding. cp852 and cp1250

cp852
```
e:\NET\__DwarfFotress_translate\translate_client\df-translation-client-develop>python df-translate.pyw
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Gotrek\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "e:\NET\__DwarfFotress_translate\translate_client\df-translation-client-develop\frames\frame_translate_external_files.py", line 189, in <lambda>
    ttk.Button(self, text='Translate', command=lambda: self.bt_search(translate=True)).grid(row=5, column=1)
  File "e:\NET\__DwarfFotress_translate\translate_client\df-translation-client-develop\frames\frame_translate_external_files.py", line 129, in bt_search
    for filename in func(po_file_path, cur_dir, self.combo_encoding.get()):
  File "C:\Users\Gotrek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\df_gettext_toolkit\translate_plain_text.py", line 34, in translate_plain_text
    print(translation, file=dest)
  File "C:\Users\Gotrek\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp852.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 61-62: character maps to <undefined>
```

![image](https://user-images.githubusercontent.com/78147516/106395192-2006e600-6401-11eb-9574-79b7e2b74066.png)

Here is my cp852.py file. Just rename it. I couldn't upload directly python file:
[cp852.txt](https://github.com/dfint/df-translation-client/files/5900487/cp852.txt)

********************************************
Same error for second available encoding
cp1250
```
e:\NET\__DwarfFotress_translate\translate_client\df-translation-client-develop>python df-translate.pyw
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Gotrek\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "e:\NET\__DwarfFotress_translate\translate_client\df-translation-client-develop\frames\frame_translate_external_files.py", line 189, in <lambda>
    ttk.Button(self, text='Translate', command=lambda: self.bt_search(translate=True)).grid(row=5, column=1)
  File "e:\NET\__DwarfFotress_translate\translate_client\df-translation-client-develop\frames\frame_translate_external_files.py", line 129, in bt_search
    for filename in func(po_file_path, cur_dir, self.combo_encoding.get()):
  File "C:\Users\Gotrek\AppData\Local\Programs\Python\Python38-32\lib\site-packages\df_gettext_toolkit\translate_plain_text.py", line 34, in translate_plain_text
    print(translation, file=dest)
  File "C:\Users\Gotrek\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1250.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 61-62: character maps to <undefined>
```

![image](https://user-images.githubusercontent.com/78147516/106395267-a28fa580-6401-11eb-9c08-8b9cff47e5cf.png)

My cp1250.py file, rename from txt to .py
[cp1250.txt](https://github.com/dfint/df-translation-client/files/5900488/cp1250.txt)

**Comment by insolor** [comment]
The problem not in the standard Python library files, but in the df-translation-client code. I'll check this a bit later.

**Comment by insolor** [comment]
I can't reproduce. Are you still getting this error?

**Comment by insolor** [comment]
The underlying df_gettext_toolkit module has been heavily improved so that such errors must not appear anymore. If you get the same error, please report it.
