### ISSUE TITLE
Can't run df-translate

### ISSUE THREAD

**Issue by abreu20011** [dfint/df-translation-client#3]
Run df-translate.pwy from python:
```
Traceback (most recent call last):
  File ".\df-translate.pyw", line 76, in <module>
    App(noconfig='--noconfig' in sys.argv, debug='--debug' in sys.argv).mainloop()
  File ".\df-translate.pyw", line 66, in __init__
    notebook.add(TranslateExternalFiles(notebook, self.config),
  File "D:\Documents\DF\df-translation-client\frame_translate_external_files.py", line 156, in __init__
    self.update_combo_encoding()
  File "D:\Documents\DF\df-translation-client\frame_translate_external_files.py", line 72, in update_combo_encoding
    self.combo_encoding.current(0)
  File "C:\Users\User.ARX-MAD-D014\AppData\Local\Programs\Python\Python37-32\lib\tkinter\ttk.py", line 719, in current
    return self.tk.call(self._w, "current", newindex)
_tkinter.TclError: Index 0 out of range
```

**Comment by abreu20011** [comment]
I tried it in three different computers and in all of them, the first time open, but next times don't open. Also I noticed that encoding have very problems. Not load the correct presents, leaving a blank field instead cp850, cp819, etc...

I tried this in an English and Spanish computer into Spain country.

**Comment by abreu20011** [comment]
I delete all python libs and also unistall python. But nothing, once you opened the app one time, its impossible to open again :S
